### ISSUE TITLE
Problem with Caribou compilation

### ISSUE THREAD

**Issue by ateixeira0163** [mimesis-inria/caribou#96]
After updating SOFA to v21.12.00 (compiling from the source) and recompiling Caribou also from the sources I got some problems apparently with the variable `SOFA_VERSION`. The error while building caribou starts as follow:

```
[ 20%] Building CXX object src/SofaCaribou/CMakeFiles/SofaCaribou.dir/Algebra/BaseVectorOperations.cpp.o
In file included from /home/user/Sofa/caribou/src/SofaCaribou/Algebra/BaseVectorOperations.cpp:7:
/home/user/Sofa/build/install/include/Sofa.Compat/sofa/defaulttype/BaseVector.h:31:11: error: conflicting declaration ‘using BaseVector = class sofa::linearalgebra::BaseVector’
   31 |     using BaseVector = sofa::linearalgebra::BaseVector;
      |           ^~~~~~~~~~
In file included from /home/user/Sofa/caribou/src/SofaCaribou/Algebra/BaseVectorOperations.cpp:2:
/home/user/Sofa/caribou/src/SofaCaribou/../SofaCaribou/Algebra/BaseVectorOperations.h:14:11: note: previous declaration as ‘class sofa::defaulttype::BaseVector’
   14 |     class BaseVector;
      |           ^~~~~~~~~~
```

Upon research on the file `~/Sofa/build/install/include/Sofa.Config/sofa/version.h`, I saw that the `SOFA_VERSION` seems well defined : 

```cpp
#ifndef SOFA_VERSION_H
#define SOFA_VERSION_H

#define SOFA_VERSION_STR "21.12.00"

// We use version numbers based on the date: yy.mm.pp (year, month, patch).
// - SOFA_VERSION / 10000 is the year number
// - SOFA_VERSION / 100 % 100 is the month number
// - SOFA_VERSION % 100 is the patch number
#define SOFA_VERSION 211200

#endif
```
And as for the the file `Algebra/BaseVectorOperations.cpp`:

```cpp
#include <sofa/version.h>
#if (defined(SOFA_VERSION) && SOFA_VERSION < 211299)
#include <sofa/defaulttype/BaseVector.h>
#else
#include <sofa/linearalgebra/BaseVector.h>
#endif // #if (defined(SOFA_VERSION) && SOFA_VERSION < 211299)
#include <SofaBaseLinearSolver/FullVector.h>
```
Thanks.

**Comment by jnbrunet** [comment]
Hey @ateixeira0163 

Thanks for the report. This issue should be fix by https://github.com/jnbrunet/caribou/pull/95 . I'm struggling a bit with MacOS CI but I will try to merge it this evening or tomorrow. If you can't wait, you can safely checkout the PR's branch or simply cherry-pick [this commit](https://github.com/jnbrunet/caribou/pull/95/commits/35ad32267f67e6168581c8fd47efee13d1427d48), the CI issue isn't related.

**Comment by jnbrunet** [comment]
Alright, #95 has been merged. I will therefore close this issue. Don't hesitate to reopen it if it didn't help.

Thanks again for the report.

**Comment by ateixeira0163** [comment]
Thanks! Everything is working fine!
